---
spring:
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/battleships
    username: root
    password: passworD
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  jackson:
    mapper:
      accept-case-insensitive-enums: true

server:
  port: 9721
